export const CHANGE_SEARCH_FIELD: string = "CHANGE_SEARCH_FIELD";

export const REQEST_ROBOTS_PENDING: string = "REQEST_ROBOTS_PENDING";
export const REQEST_ROBOTS_SUCCESS: string = "REQEST_ROBOTS_SUCCESS";
export const REQEST_ROBOTS_FAILED: string = "REQEST_ROBOTS_FAILED";
