export const CHANGE_SEARCH_FIELD = "CHANGE_SEARCH_FIELD";

export const REQEST_ROBOTS_PENDING = "REQEST_ROBOTS_PENDING";
export const REQEST_ROBOTS_SUCCESS = "REQEST_ROBOTS_SUCCESS";
export const REQEST_ROBOTS_FAILED = "REQEST_ROBOTS_FAILED";
